export const SYSTEM_CONFIG = {
  WITHDRAW_FEE: 0,
  SYSTEM_CURRENCY: '',
  ADMIN_EMAIL: "Administrator<carcaresytem@gmail.com>, Chi Cong<maichicong1999@gmail.com>",
  CALLING_CARD: 4000,
  PERIOD: 168,
  ESCROW_PERIOD: 6,
  LOAN_RATE: 0.03,
  BONUS_BLOCK_PERCENT: 0.3,
  BONUS_MATCHING_PERCENT: 0.1,
  WEB_EXPIRED_PERIOD: 28,
  NOTIFY_REGISTER_EMAIL: '"Mondex Card Registration" <carcaresytem@gmail.com>',
  NOTIFY_CHANGE_PASSWORD_EMAIL: '"Mondex Card" <carcaresytem@gmail.com>',
  NOTIFY_WITHDRAW_EMAIL: 'carcaresytem@gmail.com',
  NOTIFY_ADD_FUND_EMAIL: 'carcaresytem@gmail.com',
  NOTIFY_KYC: '"Mondex KYC" <carcaresytem@gmail.com>',
  NOTIFY_AUTO_REPLY_EMAIL: 'carcaresytem@gmail.com',
  NOTIFY_NOTICE_EMAIL: '"Mondex Notice" <carcaresytem@gmail.com>',
  NOTIFY_PURCHASE_EMAIL: '"MondexTel Purchase Request" <carcaresytem@gmail.com>',
  DEFAULT_AGENT_ID: 3
};
